# .streamlit/secrets.toml
[connections.snowflake]
account = 'ZUDZMSU-AAB45354'
user = 'KSHAW12'
password = 'FoundationsDone3@'
role = 'SYSADMIN'
warehouse = 'COMPUTE_WH'
database = 'SMOOTHIES'
schema = 'PUBLIC'
client_session_keep_alive = true

DB_USERNAME = "KSHAW12"
DB_TOKEN = "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"
